//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_2024.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_tasks
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> id_perform_task { get; set; }
    
        public virtual PerformTasks PerformTasks { get; set; }
        public virtual User User { get; set; }
    }
}
